core/urls.py
from django.urls import path
from .views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductListView,\
    ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView, ExpenseListView, homepage, KirimCreateView, \
    KirimUpdateView, KirimDeleteView, KirimListView, ChiqimCreateView, ChiqimUpdateView, ChiqimDeleteView, \
    ChiqimListView


app_name = "core"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('product/add_product/', ProductCreateView.as_view(), name='add_product'),
    path('product/<int:pk>/product_update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/product_delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('kirim/add_kirim/', KirimCreateView.as_view(), name='add_kirim'),
    path('kirim/<int:pk>/kirim_update/', KirimUpdateView.as_view(), name='kirim_update'),
    path('kirim/<int:pk>/kirim_delete/', KirimDeleteView.as_view(), name='kirim_delete'),
    path('kirim_list/', KirimListView.as_view(), name='kirim_list'),
    path('chiqim/add_chiqim/', ChiqimCreateView.as_view(), name='add_chiqim'),
    path('chiqim/<int:pk>/chiqim_update/', ChiqimUpdateView.as_view(), name='chiqim_update'),
    path('chiqim/<int:pk>/chiqim_delete/', ChiqimDeleteView.as_view(), name='chiqim_delete'),
    path('chiqim_list/', ChiqimListView.as_view(), name='chiqim_list'),
    path('expense/expense_add/', ExpenseCreateView.as_view(), name='expense_add'),
    path('expense/<int:pk>/expense_update/', ExpenseUpdateView.as_view(), name='expense_update'),
    path('product/<int:pk>/expense_delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expense_list/', ExpenseListView.as_view(), name='expense_list'),
]

hisab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('sales/', include('sales.urls')),

]

sales/urls.py
from django.urls import path
from .views import CustomerCreateView, CustomerListView, CustomerUpdateView, CustomerDeleteView, homepage, \
    OrderCreateView, OrderUpdateView, OrderListView, OrderDeleteView, PaymentCreateView, PaymentUpdateView, \
    PaymentDeleteView, PaymentListView

app_name = "sales"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('customer/customer_add/', CustomerCreateView.as_view(), name='customer_add'),
    path('customer/<int:pk>/customer_update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/<int:pk>/customer_delete/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('customer_list/', CustomerListView.as_view(), name='customer_list'),
    path('order/order_add/', OrderCreateView.as_view(), name='order_add'),
    path('order/<int:pk>/order_update/', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/order_delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('order_list/', OrderListView.as_view(), name='order_list'),
    path('payment/payment_add/', PaymentCreateView.as_view(), name='payment_add'),
    path('payment/<int:pk>/payment_update/', PaymentUpdateView.as_view(), name='payment_update'),
    path('payment/<int:pk>/payment_delete/', PaymentDeleteView.as_view(), name='payment_delete'),
    path('payment_list/', PaymentListView.as_view(), name='payment_list'),

]

sales/models.py
from django.db import models
from core.models import Product
from django.utils.translation import gettext_lazy as _


class Customer(models.Model):
    kompaniya_nomi = models.CharField(max_length=255, null=True, blank=True)
    ismi = models.CharField(max_length=255)
    manzili = models.TextField()
    telefon_raqami = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ismi


class Order(models.Model):
    ORDER_TYPE_CHOICES = [
        ('dona', _('Chakana')),
        ('ulgurji', _('Ulgurji')),
    ]
    ORDER_STATUS_CHOICES = [
        ('kutilyapti', _('Kutilyapti')),
        ('tasdiqlandi', _('Tasdiqlandi')),
        ('yetkazildi', _('Yetkazildi')),
        ('bekor qilindi', _('Bekor qilindi')),
    ]
    CURRENCY_TYPE_CHOICES = [
        ('USD', _('US Dollar')),
        ('UZS', _('Uzbekistan Sum')),
        ('RUB', _('Russian Ruble')),
    ]

    tovar = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders')
    valyuta_turi = models.CharField(max_length=3, choices=CURRENCY_TYPE_CHOICES)
    mijoz = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='orders')
    sana = models.DateField()
    buyurtma_miqdori = models.PositiveIntegerField(default=0)
    buyurtma_turi = models.CharField(max_length=255, choices=ORDER_TYPE_CHOICES)
    buyurtma_holati = models.CharField(max_length=255, choices=ORDER_STATUS_CHOICES)

    def __str__(self):
        return str(self.tovar.nomi)


class Transaction(models.Model):
    CURRENCY_TYPE_CHOICES = [
        ('USD', 'US Dollar'),
        ('UZS', 'Uzbekistan Sum'),
        ('RUB', 'Russian Ruble'),
    ]
    PAYMENT_CHOICE = [
        ("Naqd", "Naqd"),
        ("Pul o'tkazish", "Pul o'tkazish yo'li bilan"),

    ]
    PAYMENT_STATUS = [
        ("To'liq to'landi", "To'liq to'landi"),
        ("Qisman to'landi", "Qisman to'lanmadi"),
        ("To'lanmadi", "Umuman to'lanmadi"),
    ]
    buyurtma = models.ForeignKey(Order, on_delete=models.CASCADE)
    mijoz = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='transactions')
    summa = models.PositiveIntegerField()
    sana = models.DateField()
    holati = models.CharField(max_length=20, choices=PAYMENT_STATUS)
    tulov_turi = models.CharField(max_length=14, choices=PAYMENT_CHOICE)
    valyuta_turi = models.CharField(max_length=3, choices=CURRENCY_TYPE_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

sales/forms.py
from django import forms
from .models import Customer, Order, Transaction
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['kompaniya_nomi', 'ismi', 'telefon_raqami', 'manzili']

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('ismi', css_class='form-group col-md-6 mb-0'),
                Column('kompaniya_nomi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('manzili', css_class='form-group col-md-6 mb-0'),
                Column('telefon_raqami', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),

            Submit('submit', "Mijoz qo'shish")
        )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['tovar', 'valyuta_turi', 'mijoz', 'sana', 'buyurtma_miqdori', 'buyurtma_turi', 'buyurtma_holati']
        widgets = {
            'sana': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
            'buyurtma_holati': forms.Select(attrs={'class': 'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Row(
                Column('tovar', css_class='form-group col-md-4 mb-0'),
                Column('valyuta_turi', css_class='form-group col-md-4 mb-0'),
                Column('sana', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('mijoz', css_class='form-group col-md-6 mb-0'),
                Column('buyurtma_miqdori', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('buyurtma_turi', css_class='form-group col-md-6 mb-0'),
                Column('buyurtma_holati', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', "Buyurtma qo'shish")
        )

    def clean_buyurtma_miqdori(self):
        buyurtma_miqdori = self.cleaned_data['buyurtma_miqdori']
        if buyurtma_miqdori <= 0:
            raise forms.ValidationError("Buyurtma miqdori noldan katta bo'lishi kerak.")
        return buyurtma_miqdori


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['buyurtma', 'mijoz', 'summa', 'sana', 'holati', 'tulov_turi', 'valyuta_turi']
        widgets = {
            'sana': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
            'buyurtma': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('buyurtma', css_class='form-group col-md-6 mb-0'),
                Column('mijoz', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('summa', css_class='form-group col-md-6 mb-0'),
                Column('sana', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('holati', css_class='form-group col-md-4 mb-0'),
                Column('tulov_turi', css_class='form-group col-md-4 mb-0'),
                Column('valyuta_turi', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),

            Submit('submit', "To'lov qo'shish")
        )

sales/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CustomerForm, OrderForm, TransactionForm
from .models import Customer, Order, Transaction
from django_filters.views import FilterView
from .filters import OrderFilter

class OrderListFilterView(FilterView):
    model = Order
    template_name = 'sales/order_list.html'
    filterset_class = OrderFilter
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset_class(self.request.GET, queryset=self.get_queryset())
        return context


def homepage(request):
    return render(request=request, template_name="core/index.html")


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'sales/customer_add.html'
    success_url = reverse_lazy('sales:customer_list')


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'sales/customer_update.html'
    success_url = reverse_lazy('sales:customer_list')


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'sales/customer_delete.html'
    success_url = reverse_lazy('sales:customer_list')


class CustomerListView(ListView):
    model = Customer
    template_name = 'sales/customer_list.html'
    context_object_name = 'customers'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customers = context['customers']
        paginator = Paginator(customers, self.paginate_by)
        page = self.request.GET.get('customers')

        try:
            customers = paginator.page(page)
        except PageNotAnInteger:
            customers = paginator.page(1)
        except EmptyPage:
            customers = paginator.page(paginator.num_pages)

        context['customers'] = customers
        return context


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'sales/order_add.html'
    success_url = reverse_lazy('sales:order_list')


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'sales/order_update.html'
    success_url = reverse_lazy('sales:order_list')


class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'sales/order_delete.html'
    success_url = reverse_lazy('sales:order_list')


class OrderListView(ListView):
    model = Order
    template_name = 'sales/order_list.html'
    context_object_name = 'order_list'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_list = context['order_list']
        paginator = Paginator(order_list, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            order_list = paginator.page(page)
        except PageNotAnInteger:
            order_list = paginator.page(1)
        except EmptyPage:
            order_list = paginator.page(paginator.num_pages)

        context['order_list'] = order_list
        return context



class PaymentCreateView(CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'sales/payment_add.html'
    success_url = reverse_lazy('sales:payment_list')


class PaymentUpdateView(UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'sales/payment_update.html'
    success_url = reverse_lazy('sales:payment_list')


class PaymentDeleteView(DeleteView):
    model = Transaction
    template_name = 'sales/payment_delete.html'
    success_url = reverse_lazy('sales:payment_list')


class PaymentListView(ListView):
    model = Transaction
    template_name = 'sales/payment_list.html'
    context_object_name = 'transactions'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        transactions = context['transactions']
        paginator = Paginator(transactions, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            transactions = paginator.page(page)
        except PageNotAnInteger:
            transactions = paginator.page(1)
        except EmptyPage:
            transactions = paginator.page(paginator.num_pages)

        context['transactions'] = transactions
        return context

sales/templates/sales/customer_add.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>Mijoz qo'shish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">Mijoz qo'shish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sales/templates/sales/customer_delete.html
{% extends "core/index.html" %}

{% block content %}
<div class="card-body">
    <h5>Mijozni o'chirish</h5>
    <form method="post">
        {% csrf_token %}
        <p> <strong>{{ object.ismi }} </strong> ni ro'yxatdan o'chirishni istaysizmi? </p>
        <button type="submit" class="btn btn-danger">O'chirish<span class="fe fe-trash-2 fs-14"></span></button>
        <a type="button" class="btn btn-warn" href="{%url 'sales:customer_list' %}">Bekor qilish
        </a>
    </form>
</div>
{% endblock %}

sales/templates/sales/customer_list.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}


<div class="row mt-5">
    <div class="col-12 col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title mb-0">Mijozlar ro'yxati</h3>
                                    </div>

                                    <div class="card-body pt-4">
                                        <div class="grid-margin">
                                            <div class="">
                                                <div class="panel panel-primary">
                                                    <div class="d-flex justify-content-end mb-3">
                                                      <a href="{% url 'sales:customer_add' %}" class="btn btn-primary">
                                                          <span class="fe fe-plus me-2"></span>Mijoz qo'shish</a>
                                                    </div>

                                                    <div class="panel-body tabs-menu-body border-0 pt-0">
                                                        <div class="tab-content">
                                                            <div class="tab-pane active" id="tab5">
                                                                <div class="table-responsive">
                                                                    <table id="data-table"
                                                                        class="table table-bordered text-nowrap mb-0">
                                                                        <thead class="border-top">
                                                                            <tr>


                                                                                <th class="bg-transparent border-bottom-0"
                                                                                    style="width: 15%;">Kompaniya nomi</th>
                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                    Menejer ismi</th>

                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                   Telefon raqami</th>
                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                    Manzili</th>

                                                                                <th class="bg-transparent border-bottom-0"
                                                                                    style="width: 5%;">O'zgartirish</th>
                                                                            </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                            {% for customer in object_list %}
                                                                            <tr class="border-bottom">

                                                                                <td><span class="mt-sm-2 d-block">
                                                                                    {{ customer.kompaniya_nomi }}
                                                                                </span></td>
                                                                                <td>
                                                                                    <div class="mt-sm-1 d-block">
                                                                                        <span
                                                                                            class="badge bg-success-transparent rounded-pill text-success p-2 px-3">{{ customer.ismi  }}</span>
                                                                                    </div>
                                                                                </td>
                                                                                <td><span
                                                                                        class="fw-semibold mt-sm-2 d-block">{{ customer.telefon_raqami}}</span>
                                                                                </td>
                                                                                <td>
                                                                                    <div class="d-flex">
                                                                                        <div
                                                                                            class="mt-0 mt-sm-3 d-block">
                                                                                            <h6
                                                                                                class="mb-0 fs-14 fw-semibold">
                                                                                                {{ customer.manzili}}</h6>
                                                                                        </div>
                                                                                    </div>
                                                                                </td>

                                                                                <td>
                                                                                    <div class="g-2">
                                                                                        <a href="{% url 'sales:customer_update' pk=customer.pk%}"
                                                                                          class="btn text-primary btn-sm"
                                                                                            data-bs-toggle="tooltip"
                                                                                            data-bs-original-title="Tahrirlash"><span
                                                                                                class="fe fe-edit fs-14"></span></a>
                                                                                        <a href="{% url 'sales:customer_delete' pk=customer.pk%}"
                                                                                           class="btn text-danger btn-sm"
                                                                                            data-bs-toggle="tooltip"
                                                                                            data-bs-original-title="O'chirish"><span
                                                                                                class="fe fe-trash-2 fs-14"></span></a>
                                                                                    </div>
                                                                                </td>
                                                                            </tr>
                                                                             {% endfor %}
                                                                        </thead>

                                                                        </tbody>
                                                                    </table>
                                                                    {% if is_paginated %}
                                                                              <nav class="pagination text-center mt-2">
                                                                                <span class="page-links">
                                                                                  {% if page_obj.has_previous %}
                                                                                    <a href="?page=1">&laquo; birinchi</a>
                                                                                    <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; oldingi</a>
                                                                                  {% endif %}

                                                                                  <span class="page-current">
                                                                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                                                                  </span>

                                                                                  {% if page_obj.has_next %}
                                                                                    <a href="?page={{ page_obj.next_page_number }}">keyingi &rsaquo;</a>
                                                                                    <a href="?page={{ page_obj.paginator.num_pages }}">so'ngi &raquo;</a>
                                                                                  {% endif %}
                                                                                </span>
                                                                              </nav>
                                                                   {% endif %}

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- ROW-4 END -->
</div>
                    <!-- CONTAINER END -->


{% endblock %}

sales/templates/sales/customer_update.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card-body">
    <h5>Mijozni tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'sales:customer_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}

sales/templates/sales/order_add.html
{% extends "core/index.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>Buyurtma qo'shish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">Buyurtma qo'shish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sales/templates/sales/order_delete.html
{% extends "core/index.html" %}

{% block content %}
<div class="card-body">
    <h5>Buyurtmani o'chirish</h5>
    <form method="post">
        {% csrf_token %}
        <p> <strong>{{ object. }} </strong> ni ro'yxatdan o'chirishni istaysizmi? </p>
        <button type="submit" class="btn btn-danger">O'chirish<span class="fe fe-trash-2 fs-14"></span></button>
        <a type="button" class="btn btn-warn" href="{%url 'sales:order_list' %}">Bekor qilish
        </a>
    </form>
</div>
{% endblock %}

sales/templates/sales/order_update.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card-body">
    <h5>Buyurtmani tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'sales:order_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}

sales/templates/sales/payment_add.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>To'lov qo'shish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">To'lov qo'shish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sales/templates/sales/payment_delete.html
{% extends "core/index.html" %}

{% block content %}
<div class="card-body">
    <h5>To'lovni o'chirish</h5>
    <form method="post">
        {% csrf_token %}
        <p> <strong>{{ object.summa }} </strong> ni ro'yxatdan o'chirishni istaysizmi? </p>
        <button type="submit" class="btn btn-danger">O'chirish<span class="fe fe-trash-2 fs-14"></span></button>
        <a type="button" class="btn btn-warn" href="{%url 'sales:payment_list' %}">Bekor qilish
        </a>
    </form>
</div>
{% endblock %}

sales/templates/sales/payment_update.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card-body">
    <h5>To'lovni tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'sales:payment_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}