core/urls.py
from django.urls import path
from .views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductListView,\
    ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView, ExpenseListView, homepage, KirimCreateView, \
    KirimUpdateView, KirimDeleteView, KirimListView, ChiqimCreateView, ChiqimUpdateView, ChiqimDeleteView, \
    ChiqimListView


app_name = "core"

urlpatterns = [
    path("", homepage, name="homepage"),
    path('product/add_product/', ProductCreateView.as_view(), name='add_product'),
    path('product/<int:pk>/product_update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/product_delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('kirim/add_kirim/', KirimCreateView.as_view(), name='add_kirim'),
    path('kirim/<int:pk>/kirim_update/', KirimUpdateView.as_view(), name='kirim_update'),
    path('kirim/<int:pk>/kirim_delete/', KirimDeleteView.as_view(), name='kirim_delete'),
    path('kirim_list/', KirimListView.as_view(), name='kirim_list'),
    path('chiqim/add_chiqim/', ChiqimCreateView.as_view(), name='add_chiqim'),
    path('chiqim/<int:pk>/chiqim_update/', ChiqimUpdateView.as_view(), name='chiqim_update'),
    path('chiqim/<int:pk>/chiqim_delete/', ChiqimDeleteView.as_view(), name='chiqim_delete'),
    path('chiqim_list/', ChiqimListView.as_view(), name='chiqim_list'),
    path('expense/expense_add/', ExpenseCreateView.as_view(), name='expense_add'),
    path('expense/<int:pk>/expense_update/', ExpenseUpdateView.as_view(), name='expense_update'),
    path('product/<int:pk>/expense_delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expense_list/', ExpenseListView.as_view(), name='expense_list'),
]

hisab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('sales/', include('sales.urls')),

]

core/models.py
from django.db import models
from django.urls import reverse

class Kirim(models.Model):
    miqdori = models.PositiveIntegerField()
    sana = models.DateField()

class Chiqim(models.Model):
    miqdori = models.ForeignKey(Kirim, on_delete=models.CASCADE)
    sana = models.DateField()




class Product(models.Model):
    UNIT_CHOICES = [
        ('kg', 'Kilogram'),
        ('lt', 'Litr'),
        ('dona', 'Dona'),
        ('m', 'Metr'),
        ('qop', "Qop"),
        ('quti', "Yashik,Qadoq")

    ]
    nomi = models.CharField(max_length=255)
    tavsifi = models.TextField()
    tannarxi = models.DecimalField(max_digits=10, decimal_places=2)
    sotilish_narxi = models.DecimalField(max_digits=10, decimal_places=2)
    miqdori = models.PositiveIntegerField()
    ulchov_birligi = models.CharField(choices=UNIT_CHOICES, max_length=20)
    kategoriyasi = models.CharField(max_length=255)
    taminotchi = models.CharField(max_length=255)
    qutidagi_tovar_soni = models.PositiveIntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.nomi



class Supplier(models.Model):
    nomi = models.CharField(max_length=255)
    manzili = models.TextField()
    telefon_raqami = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nomi


class Warehouse(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    capacity = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    last_restocked_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.product


class Expenses(models.Model):
    xarajat_nomi = models.CharField(max_length=255)
    maqsadi = models.TextField()
    miqdori = models.DecimalField(max_digits=10, decimal_places=2)
    CURRENCY_TYPE_CHOICES = [
        ('USD', 'US Dollar'),
        ('UZS', 'Uzbekistan Sum'),
        ('RUB', 'Russian Ruble'),
    ]
    valyuta_turi = models.CharField(max_length=3, choices=CURRENCY_TYPE_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Xarajatlar"

    def __str__(self):
        return self.xarajat_nomi

    def get_absolute_url(self):
        return reverse('expense_detail', args=[str(self.id)])





#
# class SalesReport(models.Model):
#     order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True, related_name='sales_reports')
#     order_item = models.ForeignKey(OrderItem, on_delete=models.SET_NULL, blank=True, null=True, related_name='sales_reports')
#     start_date = models.DateField()
#     end_date = models.DateField()
#     total_sales = models.DecimalField(max_digits=10, decimal_places=2)
#     total_profit = models.DecimalField(max_digits=10, decimal_places=2)
#     total_customers = models.IntegerField()
#     total_items_sold = models.IntegerField()
#     top_selling_products = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

core/forms.py
from django import forms
from .models import Product, Expenses, Kirim, Chiqim
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column


class KirimForm(forms.ModelForm):

    class Meta:
        model = Kirim
        fields = ['miqdori', 'sana']
        widgets = {
            'sana': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
                  }

    def __init__(self, *args, **kwargs):
        super(KirimForm, self).__init__(*args, **kwargs)

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('miqdori', css_class='form-group col-md-6 mb-0'),
                Column('sana', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', "Kirim qilish")
        )


class ChiqimForm(forms.ModelForm):
    class Meta:
        model = Kirim
        fields = ['miqdori', 'sana']
        widgets = {
            'sana': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
                  }

    def __init__(self, *args, **kwargs):
        super(ChiqimForm, self).__init__(*args, **kwargs)

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('miqdori', css_class='form-group col-md-6 mb-0'),
                Column('sana', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', "Chiqim qilish")
        )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['nomi', 'tavsifi', 'tannarxi', 'sotilish_narxi', 'miqdori', 'ulchov_birligi', 'qutidagi_tovar_soni',
                  'kategoriyasi', 'taminotchi']
        widgets = {
            'ulchov_birligi': forms.Select(attrs={'class': 'unit_field'}),
        }

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['ulchov_birligi'].choices = Product.UNIT_CHOICES

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('nomi', css_class='form-group col-md-6 mb-0'),
                Column('kategoriyasi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('tavsifi', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('tannarxi', css_class='form-group col-md-6 mb-0'),
                Column('sotilish_narxi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('miqdori', css_class='form-group col-md-6 mb-0'),
                Column('ulchov_birligi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('qutidagi_tovar_soni', css_class='form-group col-md-6 mb-0'),
                Column('taminotchi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', "Tovar qo'shish")
        )


class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = ['xarajat_nomi', 'maqsadi', 'miqdori', 'valyuta_turi']

    def __init__(self, *args, **kwargs):
        super(ExpensesForm, self).__init__(*args, **kwargs)

        # create a helper object
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        # define form layout using crispy-forms layout objects
        self.helper.layout = Layout(
            Row(
                Column('xarajat_nomi', css_class='form-group col-md-6 mb-0'),
                Column('valyuta_turi', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('maqsadi', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('miqdori', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', "Xarajat kiritish")
        )

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import ProductForm, ExpensesForm, KirimForm, ChiqimForm
from .models import Product, Expenses, Kirim, Chiqim


def homepage(request):
    return render(request=request, template_name="core/index.html")


class KirimCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/add_kirim.html'
    success_url = reverse_lazy('core:kirim_list')


class KirimUpdateView(UpdateView):
    model = Kirim
    form_class = KirimForm
    template_name = 'core/kirim_update.html'
    success_url = reverse_lazy('core:kirim_list')


class KirimDeleteView(DeleteView):
    model = Kirim
    template_name = 'core/kirim_delete.html'
    success_url = reverse_lazy('core:kirim_list')


class KirimListView(ListView):
    model = Kirim
    template_name = 'core/kirim_list.html'
    context_object_name = 'kirims'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kirims = context['kirims']
        paginator = Paginator(kirims, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            kirims = paginator.page(page)
        except PageNotAnInteger:
            kirims = paginator.page(1)
        except EmptyPage:
            kirims = paginator.page(paginator.num_pages)

        context['kirims'] = kirims
        return context

class ChiqimCreateView(CreateView):
    model = Chiqim
    form_class = ChiqimForm
    template_name = 'core/add_chiqim.html'
    success_url = reverse_lazy('core:chiqim_list')


class ChiqimUpdateView(UpdateView):
    model = Chiqim
    form_class = ChiqimForm
    template_name = 'core/chiqim_update.html'
    success_url = reverse_lazy('core:chiqim_list')


class ChiqimDeleteView(DeleteView):
    model = Chiqim
    template_name = 'core/chiqim_delete.html'
    success_url = reverse_lazy('core:chiqim_list')


class ChiqimListView(ListView):
    model = Chiqim
    template_name = 'core/chiqim_list.html'
    context_object_name = 'chiqims'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chiqims = context['chiqims']
        paginator = Paginator(chiqims, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            chiqims = paginator.page(page)
        except PageNotAnInteger:
            chiqims = paginator.page(1)
        except EmptyPage:
            chiqims = paginator.page(paginator.num_pages)

        context['chiqims'] = chiqims
        return context


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/add_product.html'
    success_url = reverse_lazy('core:product_list')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'core/product_update.html'
    success_url = reverse_lazy('core:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'core/product_delete.html'
    success_url = reverse_lazy('core:product_list')


class ProductListView(ListView):
    model = Product
    template_name = 'core/product_list.html'
    context_object_name = 'products'
    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context['products']
        paginator = Paginator(products, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context['products'] = products
        return context


class ExpenseCreateView(CreateView):
    model = Expenses
    form_class = ExpensesForm
    template_name = 'core/expense_add.html'
    success_url = reverse_lazy('core:expense_list')


class ExpenseUpdateView(UpdateView):
    model = Expenses
    form_class = ExpensesForm
    template_name = 'core/expense_update.html'
    success_url = reverse_lazy('core:expense_list')


class ExpenseDeleteView(DeleteView):
    model = Expenses
    form_class = ExpensesForm
    template_name = 'core/expense_delete.html'
    success_url = reverse_lazy('core:expense_list')


class ExpenseListView(ListView):
    model = Expenses
    template_name = 'core/expense_list.html'
    context_object_name = 'expenses'

    paginate_by = 10  # number of products per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        expenses = context['expenses']
        paginator = Paginator(expenses, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            expenses = paginator.page(page)
        except PageNotAnInteger:
            expenses = paginator.page(1)
        except EmptyPage:
            expenses = paginator.page(paginator.num_pages)

        context['expenses'] = expenses
        return context

core/templates/core/add_chiqim.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>Chiqm qilish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">Chiqim qo'shish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

core/templates/core/add_kirim.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>Kirim qilish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">Kirim qo'shish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-q3aZ0J+v1f5cVr43xlxJGz7FAF5HG+t8ZJfzZh5O5v5O5L+8xuJz5O5vm9KvBV8W" crossorigin="anonymous"></script>
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

core/templates/core/chiqim_list.html
{% extends "core/index.html" %}

{% block content %}
  {% endblock %}

core/templates/core/expense_add.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}

<div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h3>Xarajat kiritish</h3>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary mt-3">Xarajat kiritish</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/expense_delete.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<div class="card-body modal-center">
    <h5>Xarajat o'chirish</h5>
    <form method="post">
        {% csrf_token %}
        <p> <strong>{{ object.xarajat_nomi }} </strong> ni ro'yxatdan o'chirishni istaysizmi? </p>
        <button type="submit" class="btn btn-danger">O'chirish<span class="fe fe-trash-2 fs-14"></span></button>
        <a type="button" class="btn btn-success" href="{%url 'core:expense_list' %}">Bekor qilish
        </a>
    </form>
</div>

{% endblock %}

core/templates/core/expense_list.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}

{% block content %}


<div class="row mt-5">
    <div class="col-12 col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title mb-0">Xarajatlar ro'yxati</h3>
                                    </div>
                                    <div class="card-body pt-4">
                                        <div class="grid-margin">
                                            <div class="">
                                                <div class="panel panel-primary">
                                                    <div class="d-flex justify-content-end mb-3">
                                                      <a href="{% url 'core:expense_add' %}" class="btn btn-primary">
                                                          <span class="fe fe-plus me-2"></span>Xarajat qo'shish</a>
                                                    </div>
                                                    <div class="panel-body tabs-menu-body border-0 pt-0">
                                                        <div class="tab-content">
                                                            <div class="tab-pane active" id="tab5">
                                                                <div class="table-responsive">
                                                                    <table id="data-table"
                                                                        class="table table-bordered text-nowrap mb-0">
                                                                        <thead class="border-top">
                                                                            <tr>


                                                                                <th class="bg-transparent border-bottom-0"
                                                                                    style="width: 15%;">Xarajat nomi</th>
                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                    Xarajat maqsadi</th>

                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                   Xarajat miqdori</th>
                                                                                <th
                                                                                    class="bg-transparent border-bottom-0">
                                                                                    Valyuta turi</th>

                                                                                <th class="bg-transparent border-bottom-0"
                                                                                    style="width: 5%;">O'zgartirish</th>
                                                                            </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                            {% for expense in object_list %}
                                                                            <tr class="border-bottom">

                                                                                <td><span class="mt-sm-2 d-block">
                                                                                    {{ expense.xarajat_nomi }}
                                                                                </span></td>
                                                                                <td>
                                                                                    <div class="mt-sm-1 d-block">
                                                                                        <span
                                                                                            class="badge bg-success-transparent rounded-pill text-success p-2 px-3">{{ expense.maqsadi }}</span>
                                                                                    </div>
                                                                                </td>
                                                                                <td><span
                                                                                        class="fw-semibold mt-sm-2 d-block">{{ expense.miqdori }}</span>
                                                                                </td>
                                                                                <td>
                                                                                    <div class="d-flex">
                                                                                        <div
                                                                                            class="mt-0 mt-sm-3 d-block">
                                                                                            <h6
                                                                                                class="mb-0 fs-14 fw-semibold">
                                                                                                {{ expense.valyuta_turi }}</h6>
                                                                                        </div>
                                                                                    </div>
                                                                                </td>

                                                                                <td>
                                                                                    <div class="g-2">
                                                                                        <a href="{% url 'core:expense_update' pk=expense.pk%}"
                                                                                          class="btn text-primary btn-sm"
                                                                                            data-bs-toggle="tooltip"
                                                                                            data-bs-original-title="Tahrirlash"><span
                                                                                                class="fe fe-edit fs-14"></span></a>
                                                                                        <a href="{% url 'core:expense_delete' pk=expense.pk%}"
                                                                                           class="btn text-danger btn-sm"
                                                                                            data-bs-toggle="tooltip"
                                                                                            data-bs-original-title="O'chirish"><span
                                                                                                class="fe fe-trash-2 fs-14"></span></a>
                                                                                    </div>
                                                                                </td>
                                                                            </tr>
                                                                             {% endfor %}
                                                                        </thead>
                                                                        <tbody>



                                                                        </tbody>

                                                                    </table>
                                                                {% if is_paginated %}
                                                                              <nav class="pagination text-center mt-2">
                                                                                <span class="page-links">
                                                                                  {% if page_obj.has_previous %}
                                                                                    <a href="?page=1">&laquo; birinchi</a>
                                                                                    <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; oldingi</a>
                                                                                  {% endif %}

                                                                                  <span class="page-current">
                                                                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                                                                  </span>

                                                                                  {% if page_obj.has_next %}
                                                                                    <a href="?page={{ page_obj.next_page_number }}">keyingi &rsaquo;</a>
                                                                                    <a href="?page={{ page_obj.paginator.num_pages }}">so'ngi &raquo;</a>
                                                                                  {% endif %}
                                                                                </span>
                                                                              </nav>
                                                                   {% endif %}

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- ROW-4 END -->
</div>
                    <!-- CONTAINER END -->


{% endblock %}

core/templates/core/expense_update.html
{% extends "core/index.html" %}


{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<div class="card-body">
    <h5>Xarajatlarni tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'core:expense_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}

core/templates/core/kirim_list.html
{% extends "core/index.html" %}

{% block content %}
  {% endblock %}

core/templates/core/kirim_update.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card-body">
    <h5>Kirimni tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'core:kirim_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}

core/templates/core/product_update.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card-body">
    <h5>Tovarni tahrirlash</h5>
    <form method="post">
        {% csrf_token %}
         {{ form|crispy }}
        <a type="button" class="btn btn-danger" href="{%url 'core:product_list' %}">Bekor qilish</a>
        <button type="submit" class="btn btn-success">Yangilash</button>
    </form>
</div>

{% endblock %}